/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lfp.proyecto_final_201709426.View;

import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import lfp.proyecto_final_201709426.Controller.Analisis_Lexico;
import lfp.proyecto_final_201709426.Controller.Analisis_Sintactico;
import lfp.proyecto_final_201709426.Controller.Reports;
import lfp.proyecto_final_201709426.Model.Errror;
import lfp.proyecto_final_201709426.Model.Noticia;
import lfp.proyecto_final_201709426.Model.Token;

/**
 *
 * @author Samuel
 */
public class Editor extends javax.swing.JFrame {

    ArrayList<Token> lista_token = new ArrayList();
    ArrayList<Errror> errores_lexicos = new ArrayList();
    ArrayList<Errror> errores_sintaciticos = new ArrayList();
    ArrayList<Noticia> noticias = new ArrayList();
    Noticia noticia = new Noticia();

    /**
     * Creates new form Editor
     */
    public Editor() {
        initComponents();
        this.setTitle("Diario “La Otra Perspectiva”");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txt_editor = new javax.swing.JTextArea();
        btn_analizar = new javax.swing.JButton();
        btn_visualizar = new javax.swing.JButton();
        btn_publicar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_consola = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_archivo = new javax.swing.JMenu();
        jmi_abrir = new javax.swing.JMenuItem();
        jmi_guardar = new javax.swing.JMenuItem();
        jmi_limpiar = new javax.swing.JMenuItem();
        jmi_salir = new javax.swing.JMenuItem();
        jm_analisis = new javax.swing.JMenu();
        jmi_analizar = new javax.swing.JMenuItem();
        jmi_visualizar = new javax.swing.JMenuItem();
        jmi_publicar = new javax.swing.JMenuItem();
        jm_noticias = new javax.swing.JMenu();
        jm_noticia_dia = new javax.swing.JMenu();
        jm_noticia = new javax.swing.JMenu();
        jm_farandula = new javax.swing.JMenu();
        jm_deportes = new javax.swing.JMenu();
        jm_publicidad = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jmi_manual_usuario = new javax.swing.JMenuItem();
        jmi_manual_tec = new javax.swing.JMenuItem();
        jmi_acerca_de = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        txt_editor.setColumns(20);
        txt_editor.setRows(5);
        jScrollPane1.setViewportView(txt_editor);

        btn_analizar.setText("Analizar");
        btn_analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_analizarActionPerformed(evt);
            }
        });

        btn_visualizar.setText("Visualizar");
        btn_visualizar.setEnabled(false);
        btn_visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_visualizarActionPerformed(evt);
            }
        });

        btn_publicar.setText("Publicar");
        btn_publicar.setEnabled(false);
        btn_publicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_publicarActionPerformed(evt);
            }
        });

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        txt_consola.setColumns(20);
        txt_consola.setRows(5);
        jScrollPane2.setViewportView(txt_consola);

        jLabel1.setText("Consola del sistema:");

        jLabel2.setText("EDITOR:");

        jm_archivo.setText("Archivo");

        jmi_abrir.setText("Abrir");
        jmi_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_abrirActionPerformed(evt);
            }
        });
        jm_archivo.add(jmi_abrir);

        jmi_guardar.setText("Guardar");
        jmi_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_guardarActionPerformed(evt);
            }
        });
        jm_archivo.add(jmi_guardar);

        jmi_limpiar.setText("Limpiar");
        jmi_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_limpiarActionPerformed(evt);
            }
        });
        jm_archivo.add(jmi_limpiar);

        jmi_salir.setText("Salir");
        jmi_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_salirActionPerformed(evt);
            }
        });
        jm_archivo.add(jmi_salir);

        jMenuBar1.add(jm_archivo);

        jm_analisis.setText("Analisis");

        jmi_analizar.setText("Analizar");
        jmi_analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_analizarActionPerformed(evt);
            }
        });
        jm_analisis.add(jmi_analizar);

        jmi_visualizar.setText("Visualizar");
        jmi_visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_visualizarActionPerformed(evt);
            }
        });
        jm_analisis.add(jmi_visualizar);

        jmi_publicar.setText("Publicar");
        jmi_publicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_publicarActionPerformed(evt);
            }
        });
        jm_analisis.add(jmi_publicar);

        jMenuBar1.add(jm_analisis);

        jm_noticias.setText("Noticias");
        jm_noticias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jm_noticiasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jm_noticiasMouseEntered(evt);
            }
        });

        jm_noticia_dia.setText("Noticia de Dia");
        jm_noticias.add(jm_noticia_dia);

        jm_noticia.setText("Noticias");
        jm_noticias.add(jm_noticia);

        jm_farandula.setText("Farandula");
        jm_noticias.add(jm_farandula);

        jm_deportes.setText("Deportes");
        jm_noticias.add(jm_deportes);

        jm_publicidad.setText("Publicidad");
        jm_noticias.add(jm_publicidad);

        jMenuBar1.add(jm_noticias);

        jMenu4.setText("Ayuda");

        jmi_manual_usuario.setText("Manual de Usuario");
        jmi_manual_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_manual_usuarioActionPerformed(evt);
            }
        });
        jMenu4.add(jmi_manual_usuario);

        jmi_manual_tec.setText("Manual Tecnico");
        jmi_manual_tec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_manual_tecActionPerformed(evt);
            }
        });
        jMenu4.add(jmi_manual_tec);

        jmi_acerca_de.setText("Acerca de...");
        jmi_acerca_de.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_acerca_deActionPerformed(evt);
            }
        });
        jMenu4.add(jmi_acerca_de);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_publicar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_visualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_analizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_limpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel1)))
                    .addComponent(jLabel2))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_analizar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_visualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_publicar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 262, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_analizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_analizarActionPerformed
        // TODO add your handling code here:
        analizar();
    }//GEN-LAST:event_btn_analizarActionPerformed

    public void analizar() {
        if (!txt_editor.getText().isEmpty()) {
            new Analisis_Lexico(lista_token, errores_lexicos)
                    .analizar(txt_editor.getText());
            new Analisis_Sintactico(lista_token, errores_sintaciticos, noticia).etiquetas_principales();
            txt_consola.setText(txt_consola.getText() + "\n\nSe encontraror errores, es imposible visualizar o publicar la noticia\n\n");
            if (errores_lexicos.isEmpty() && errores_sintaciticos.isEmpty()) {
                btn_visualizar.setEnabled(true);
                btn_publicar.setEnabled(true);
                jmi_publicar.setEnabled(true);
                jmi_visualizar.setEnabled(true);
                txt_consola.setText("El analisis fue realizado con exito, no ese encontro  ningun error");
            }
            JOptionPane.showMessageDialog(null, "se abrira automaticamente el archivo donde se encuentran los resultados del analisis");
            new Reports(lista_token, errores_lexicos, errores_sintaciticos).crear_reporte();
        } else {
            JOptionPane.showMessageDialog(null, "El cuadro de texto se encuetra vacio");
        }

    }

    public void limpiar() {
        txt_consola.setText("");
        txt_editor.setText("");
        lista_token = new ArrayList();
        errores_lexicos = new ArrayList();
        errores_sintaciticos = new ArrayList();
        noticia = new Noticia();
        btn_visualizar.setEnabled(false);
        btn_publicar.setEnabled(false);

        jmi_publicar.setEnabled(false);
        jmi_visualizar.setEnabled(false);
    }
    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
        limpiar();

    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_visualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_visualizarActionPerformed
        // TODO add your handling code here:
        new Vista_Previa(noticia).setVisible(true);
    }//GEN-LAST:event_btn_visualizarActionPerformed

    private void btn_publicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_publicarActionPerformed
        // TODO add your handling code here:
        noticias.add(noticia);
        limpiar();
    }//GEN-LAST:event_btn_publicarActionPerformed

    private void jm_noticiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_noticiasMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jm_noticiasMouseClicked

    private void jm_noticiasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_noticiasMouseEntered
        // TODO add your handling code here:
        jm_noticia_dia.removeAll();
        jm_noticia.removeAll();
        jm_deportes.removeAll();
        jm_farandula.removeAll();
        jm_publicidad.removeAll();

        try {
            int total = noticias.size();
            int random = (int) (Math.random() * total);
            JMenuItem item_noticia_dia = new JMenuItem(noticias.get(random).getTitulo());
            jm_noticia_dia.add(item_noticia_dia);
            item_noticia_dia.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    new Vista_Previa(noticias.get(random)).setVisible(true);
                }
            });
        } catch (Exception e) {
            JMenuItem item_noticia_dia = new JMenuItem("No hay noticias publicadas");
            jm_noticia_dia.add(item_noticia_dia);

        }

        for (int i = 0; i < noticias.size(); i++) {
            if (noticias.get(i).getTipo().equals("Noticia")) {
                JMenuItem item_noticia = new JMenuItem(noticias.get(i).getTitulo());
                item_noticia.setName(String.valueOf(i));
                item_noticia.addActionListener(new java.awt.event.ActionListener() {

                    @Override
                    public void actionPerformed(ActionEvent e) {
                        System.out.println(((JMenuItem) e.getSource()).getName());
                        int index = Integer.valueOf(((JMenuItem) e.getSource()).getName());
                        new Vista_Previa(noticias.get(index)).setVisible(true);
                    }
                });
                jm_noticia.add(item_noticia);
            } else if (noticias.get(i).getTipo().equals("Deportes")) {
                JMenuItem item_deportes = new JMenuItem(noticias.get(i).getTitulo());
                item_deportes.setName(String.valueOf(i));
                item_deportes.addActionListener(new java.awt.event.ActionListener() {

                    @Override
                    public void actionPerformed(ActionEvent e) {
                        System.out.println(((JMenuItem) e.getSource()).getName());
                        int index = Integer.valueOf(((JMenuItem) e.getSource()).getName());
                        new Vista_Previa(noticias.get(index)).setVisible(true);
                    }
                });
                jm_deportes.add(item_deportes);
            } else if (noticias.get(i).getTipo().equals("Farandula")) {
                JMenuItem item_farandula = new JMenuItem(noticias.get(i).getTitulo());
                item_farandula.setName(String.valueOf(i));
                item_farandula.addActionListener(new java.awt.event.ActionListener() {

                    @Override
                    public void actionPerformed(ActionEvent e) {
                        System.out.println(((JMenuItem) e.getSource()).getName());
                        int index = Integer.valueOf(((JMenuItem) e.getSource()).getName());
                        new Vista_Previa(noticias.get(index)).setVisible(true);
                    }
                });
                jm_farandula.add(item_farandula);
            } else if (noticias.get(i).getTipo().equals("Publicidad")) {
                JMenuItem item_publicidad = new JMenuItem(noticias.get(i).getTitulo());
                item_publicidad.setName(String.valueOf(i));
                item_publicidad.addActionListener(new java.awt.event.ActionListener() {

                    @Override
                    public void actionPerformed(ActionEvent e) {
                        System.out.println(((JMenuItem) e.getSource()).getName());
                        int index = Integer.valueOf(((JMenuItem) e.getSource()).getName());
                        new Vista_Previa(noticias.get(index)).setVisible(true);
                    }
                });
                jm_publicidad.add(item_publicidad);
            }
        }
    }//GEN-LAST:event_jm_noticiasMouseEntered

    private void jmi_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_abrirActionPerformed
        // TODO add your handling code here:
        Scanner entrada = null;
        //Se crea el JFileChooser. Se le indica que la ventana se abra en el directorio actual
        JFileChooser fileChooser = new JFileChooser(".");
        //Se crea el filtro. El primer parámetro es el mensaje que se muestra,
        //el segundo es la extensión de los ficheros que se van a mostrar      
        FileFilter filtro = new FileNameExtensionFilter("Archivos lop (.lop)", "lop");
        //Se le asigna al JFileChooser el filtro
        fileChooser.setFileFilter(filtro);
        //se muestra la ventana
        int valor = fileChooser.showOpenDialog(fileChooser);
        if (valor == JFileChooser.APPROVE_OPTION) {
            String ruta = fileChooser.getSelectedFile().getAbsolutePath();
            try {
                File f = new File(ruta);
                entrada = new Scanner(f);
                while (entrada.hasNext()) {
                    txt_editor.setText(txt_editor.getText() + "\n" + entrada.nextLine());
                }
            } catch (FileNotFoundException e) {
                System.out.println(e.getMessage());
            } finally {
                if (entrada != null) {
                    entrada.close();
                }
            }
        } else {
            System.out.println("No se ha seleccionado ningún fichero");
        }
    }//GEN-LAST:event_jmi_abrirActionPerformed

    private void jmi_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_limpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jmi_limpiarActionPerformed

    private void jmi_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_guardarActionPerformed
        // TODO add your handling code here:
        JFileChooser guardar = new JFileChooser();

        FileFilter filtro = new FileNameExtensionFilter("Archivos lop (.lop)", "lop");

        guardar.setFileFilter(filtro);
        guardar.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        guardar.showSaveDialog(null);

        File archivo = guardar.getSelectedFile();
        FileWriter escribir;
        try {

            escribir = new FileWriter(archivo, true);
            escribir.write(txt_editor.getText());
            escribir.close();

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error al guardar, ponga nombre al archivo");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error al guardar, en la salida");
        }

    }//GEN-LAST:event_jmi_guardarActionPerformed

    private void jmi_analizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_analizarActionPerformed
        // TODO add your handling code here:
        analizar();
    }//GEN-LAST:event_jmi_analizarActionPerformed

    private void jmi_visualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_visualizarActionPerformed
        // TODO add your handling code here:
        new Vista_Previa(noticia).setVisible(true);
    }//GEN-LAST:event_jmi_visualizarActionPerformed

    private void jmi_publicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_publicarActionPerformed
        // TODO add your handling code here:
        noticias.add(noticia);
        JOptionPane.showMessageDialog(null, "Se publico correctamente en la seccion de " + noticia.getTipo() + " con el titulo: " + noticia.getTitulo());
        limpiar();
    }//GEN-LAST:event_jmi_publicarActionPerformed

    private void jmi_manual_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_manual_usuarioActionPerformed
        // TODO add your handling code here:
        try {
            String url = "C:\\Users\\Samuel\\Desktop\\LFP\\[LFP]Proyecto_Final_201709426\\[LFP]Manual_de_Usuario_201709426.pdf";
            ProcessBuilder pb = new ProcessBuilder();
            pb.command("cmd.exe", "/c", url);
            pb.start();
        } catch (IOException e) {
        }
    }//GEN-LAST:event_jmi_manual_usuarioActionPerformed

    private void jmi_manual_tecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_manual_tecActionPerformed
        // TODO add your handling code here:
        try {
            String url = "C:\\Users\\Samuel\\Desktop\\LFP\\[LFP]Proyecto_Final_201709426\\[LFP]Manual_Tecnico_201709426.pdf";
            ProcessBuilder pb = new ProcessBuilder();
            pb.command("cmd.exe", "/c", url);
            pb.start();
        } catch (IOException e) {
        }
    }//GEN-LAST:event_jmi_manual_tecActionPerformed

    private void jmi_acerca_deActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_acerca_deActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Alumno: Eli Samuel Mazariegos Ramires\n"
                + "Carne: 201709426\n"
                + "Proyecto final\n"
                + "Lenguajes formales de Programacion");
    }//GEN-LAST:event_jmi_acerca_deActionPerformed

    private void jmi_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmi_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_analizar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_publicar;
    private javax.swing.JButton btn_visualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu jm_analisis;
    private javax.swing.JMenu jm_archivo;
    private javax.swing.JMenu jm_deportes;
    private javax.swing.JMenu jm_farandula;
    private javax.swing.JMenu jm_noticia;
    private javax.swing.JMenu jm_noticia_dia;
    private javax.swing.JMenu jm_noticias;
    private javax.swing.JMenu jm_publicidad;
    private javax.swing.JMenuItem jmi_abrir;
    private javax.swing.JMenuItem jmi_acerca_de;
    private javax.swing.JMenuItem jmi_analizar;
    private javax.swing.JMenuItem jmi_guardar;
    private javax.swing.JMenuItem jmi_limpiar;
    private javax.swing.JMenuItem jmi_manual_tec;
    private javax.swing.JMenuItem jmi_manual_usuario;
    private javax.swing.JMenuItem jmi_publicar;
    private javax.swing.JMenuItem jmi_salir;
    private javax.swing.JMenuItem jmi_visualizar;
    private javax.swing.JTextArea txt_consola;
    private javax.swing.JTextArea txt_editor;
    // End of variables declaration//GEN-END:variables
}
