/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lfp.proyecto_final_201709426.View;

import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import lfp.proyecto_final_201709426.Model.Noticia;

/**
 *
 * @author Samuel
 */
public class Vista_Previa extends javax.swing.JFrame {

    /**
     * Creates new form Vista_Previa
     */
    Noticia noticia = new Noticia();
    String texto = "";

    public Vista_Previa(Noticia noticia) {
        initComponents();
        this.noticia = noticia;
        this.setLocationRelativeTo(null);

        txt_img_uno.setVisible(false);
        txt_img_dos.setVisible(false);
        txt_img_tres.setVisible(false);

        lbl_uno.setVisible(false);
        lbl_dos.setVisible(false);
        lbl_tres.setVisible(false);

        btn_editar.setVisible(false);
        btn_cancelar.setVisible(false);

        txt_titulo.setText(noticia.getTitulo());
        txt_autor.setText(noticia.getAutor());
        txt_contenido.setText(noticia.getContenido());

        txt_img_uno.setText(noticia.getImagen()[0]);
        txt_img_dos.setText(noticia.getImagen()[1]);
        txt_img_tres.setText(noticia.getImagen()[2]);
        actualizar_img();
        this.setTitle(noticia.getTipo() + "-" + noticia.getTitulo());
    }

    public void actualizar_img() {

        if (noticia.getImagen()[0] != null) {
            ImageIcon img = new ImageIcon(getClass().getResource(noticia.getImagen()[0]));
            Icon fd = new ImageIcon(img.getImage().getScaledInstance(lbl_img_uno.getWidth(),
                    lbl_img_uno.getHeight(), Image.SCALE_DEFAULT));
            lbl_img_uno.setIcon(fd);
            lbl_img_uno.setText(null);
        }
        if (noticia.getImagen()[1] != null) {
            ImageIcon img = new ImageIcon(getClass().getResource(noticia.getImagen()[1]));
            Icon fd = new ImageIcon(img.getImage().getScaledInstance(lbl_img_dos.getWidth(),
                    lbl_img_dos.getHeight(), Image.SCALE_DEFAULT));
            lbl_img_dos.setIcon(fd);
            lbl_img_dos.setText(null);

        }
        if (noticia.getImagen()[2] != null) {
            ImageIcon img = new ImageIcon(getClass().getResource(noticia.getImagen()[2]));
            Icon fd = new ImageIcon(img.getImage().getScaledInstance(lbl_img_tres.getWidth(),
                    lbl_img_tres.getHeight(), Image.SCALE_DEFAULT));
            lbl_img_tres.setIcon(fd);
            lbl_img_tres.setText(null);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_contenido = new javax.swing.JTextArea();
        lbl_img_uno = new javax.swing.JLabel();
        lbl_img_dos = new javax.swing.JLabel();
        lbl_img_tres = new javax.swing.JLabel();
        txt_titulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_autor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_img_uno = new javax.swing.JTextField();
        lbl_uno = new javax.swing.JLabel();
        lbl_dos = new javax.swing.JLabel();
        txt_img_dos = new javax.swing.JTextField();
        lbl_tres = new javax.swing.JLabel();
        txt_img_tres = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btn_editar = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmi_editar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmi_guardar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        txt_contenido.setEditable(false);
        txt_contenido.setColumns(20);
        txt_contenido.setRows(5);
        jScrollPane1.setViewportView(txt_contenido);

        lbl_img_uno.setText("ImgUno");
        lbl_img_uno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lbl_img_dos.setText("ImgDos");
        lbl_img_dos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lbl_img_tres.setText("ImgTres");
        lbl_img_tres.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txt_titulo.setEditable(false);
        txt_titulo.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N

        jLabel1.setText("TITULO:");

        jLabel2.setText("AUTOR:");

        txt_autor.setEditable(false);

        jLabel3.setText("CONTENIDO:");

        txt_img_uno.setEditable(false);

        lbl_uno.setText("ImgUno:");

        lbl_dos.setText("ImgDos:");

        txt_img_dos.setEditable(false);

        lbl_tres.setText("ImgTres:");

        txt_img_tres.setEditable(false);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btn_editar.setText("EDITAR");
        btn_editar.setEnabled(false);
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_regresar.setText("REGRESAR");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("CANCELAR");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_regresar, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                        .addComponent(btn_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_regresar, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Editar");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jmi_editar.setText("Habilitar Ediccion");
        jmi_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_editarActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_editar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Exportar");

        jmi_guardar.setText("Guardar");
        jmi_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_guardarActionPerformed(evt);
            }
        });
        jMenu2.add(jmi_guardar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txt_titulo))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(txt_autor))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_img_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_img_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_uno)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_img_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_tres)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_img_tres)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_dos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_img_dos))
                                .addComponent(lbl_img_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 8, Short.MAX_VALUE))))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addComponent(jSeparator2)
            .addComponent(jSeparator4)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txt_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_img_dos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_img_uno, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_uno)
                    .addComponent(txt_img_uno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_dos)
                    .addComponent(txt_img_dos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_img_tres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tres)
                    .addComponent(txt_img_tres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu1ActionPerformed

    public void habi_desa(Boolean estado){
       txt_img_uno.setVisible(estado);
        txt_img_dos.setVisible(estado);
        txt_img_tres.setVisible(estado);

        lbl_uno.setVisible(estado);
        lbl_dos.setVisible(estado);
        lbl_tres.setVisible(estado);

        btn_editar.setVisible(estado);
        btn_cancelar.setVisible(estado);

        txt_autor.setEditable(estado);
        txt_titulo.setEditable(estado);
        txt_contenido.setEditable(estado);
        txt_img_dos.setEditable(estado);
        txt_img_uno.setEditable(estado);
        txt_img_tres.setEditable(estado);

        btn_editar.setEnabled(estado);
    }
    private void jmi_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_editarActionPerformed
        // TODO add your handling code here:       
        habi_desa(true);
    }//GEN-LAST:event_jmi_editarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        habi_desa(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        // TODO add your handling code here:
        noticia.setAutor(txt_autor.getText());
        noticia.setTitulo(txt_titulo.getText());
        noticia.setContenido(txt_contenido.getText());
        String[] imagenes = new String[3];
        imagenes[0] = txt_img_uno.getText();
        imagenes[1] = txt_img_dos.getText();
        imagenes[2] = txt_img_tres.getText();
        noticia.setImagen(imagenes);
        actualizar_img();
        habi_desa(false);
        this.setTitle(noticia.getTipo() + "-" + noticia.getTitulo());
    
        
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void jmi_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_guardarActionPerformed
        try {
            // TODO add your handling code here:
            guardarComo();
        } catch (IOException ex) {
            Logger.getLogger(Vista_Previa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmi_guardarActionPerformed

    public void guardarComo() throws IOException {
        generar_archivo();
        JFileChooser guardar = new JFileChooser();

        guardar.showSaveDialog(null);
        FileFilter filtro = new FileNameExtensionFilter("Archivos lop (.lop)", "lop");

        guardar.setFileFilter(filtro);
        guardar.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        File archivo = guardar.getSelectedFile();
        FileWriter escribir;
        try {

            escribir = new FileWriter(archivo, true);
            escribir.write(texto);
            escribir.close();
            JOptionPane.showMessageDialog(null, "Se exporto correctamente el archivo");

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error al guardar, ponga nombre al archivo");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error al guardar, en la salida");
        }

    }

    public void generar_archivo() {

        texto = texto + "<" + noticia.getTipo() + ">\n";
        texto = texto + "<Titulo>" + noticia.getTitulo() + "</Titulo>\n";
        texto = texto + "<Autor>" + noticia.getAutor() + "</Autor>\n";
        texto = texto + "<Contenido>" + noticia.getContenido() + "\n";

        if (noticia.getImagen()[0] != null) {
            texto = texto + "<ImgUno>\"" + noticia.getImagen()[0] + "\"</ImgUno>\n";
        }

        if (noticia.getImagen()[1] != null) {
            texto = texto + "<ImgDos>\"" + noticia.getImagen()[1] + "\"</ImgDos>\n";
        }

        if (noticia.getImagen()[2] != null) {
            texto = texto + "<ImgTres>\"" + noticia.getImagen()[2] + "\"</ImgTres>\n";
        }
        texto = texto + "</Contenido>\n</" + noticia.getTipo() + ">";

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Previa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Previa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Previa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Previa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Previa(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JMenuItem jmi_editar;
    private javax.swing.JMenuItem jmi_guardar;
    private javax.swing.JLabel lbl_dos;
    private javax.swing.JLabel lbl_img_dos;
    private javax.swing.JLabel lbl_img_tres;
    private javax.swing.JLabel lbl_img_uno;
    private javax.swing.JLabel lbl_tres;
    private javax.swing.JLabel lbl_uno;
    private javax.swing.JTextField txt_autor;
    private javax.swing.JTextArea txt_contenido;
    private javax.swing.JTextField txt_img_dos;
    private javax.swing.JTextField txt_img_tres;
    private javax.swing.JTextField txt_img_uno;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
